Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/annaconte/NLPatVCU/medaCy/medacy/__main__.py", line 175, in <module>
    main()
  File "/Users/annaconte/NLPatVCU/medaCy/medacy/__main__.py", line 159, in main
    args.func(args, dataset, model)
AttributeError: 'Namespace' object has no attribute 'func'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/annaconte/NLPatVCU/medaCy/medacy/__main__.py", line 175, in <module>
    main()
  File "/Users/annaconte/NLPatVCU/medaCy/medacy/__main__.py", line 159, in main
    args.func(args, dataset, model)
AttributeError: 'Namespace' object has no attribute 'func'
No filename given. Continue without saving the model at the end? (y/n) 
y
